//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPesquisaEstabelecimentoHospedagem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PesquisaEstabelecimentoHospedagemDBEntities : DbContext
    {
        public PesquisaEstabelecimentoHospedagemDBEntities()
            : base("name=PesquisaEstabelecimentoHospedagemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Estabelecimento> Estabelecimento { get; set; }
        public virtual DbSet<Quarto> Quarto { get; set; }
        public virtual DbSet<TipoQuarto> TipoQuarto { get; set; }
    }
}
