//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int IdMedico { get; set; }
        public int IdPaciente { get; set; }
        public System.DateTime Dia { get; set; }
        public System.TimeSpan Hora { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
